### ISSUE TITLE
Support `jakarta faces` in wwd-generic-editor

### ISSUE THREAD

**Issue by nimo23** [mickaelistria/eclipse-bluesky#1274]
According to https://issues.redhat.com/browse/JBIDE-28678, the `JSF component` is  removed in `JBossTools` (since version 4.28)

As stated, the code for `JSF-tooling` is open, the github repo (https://github.com/jbosstools/jbosstools-javaee).

It would be awesome to intergrate the `Faces-tooling` (= `JSF-tooling`) into wwd. Please add the **jsf-code completion** and the **outline-view** (to show the component hierarchy of the faces-webpage) into the `wwd generic editor`. The VisualPage-Editor of JSF-tooling can be ignored. But what is important: the code assist/completion of jsf components and the outline view within the wwd-generic-editor. 

Would that be possible?

**Comment by mickaelistria** [comment]
I'm not aware of a language server for JSF that we could plug in the Generic Editor to provide such assistance.

**Comment by angelozerr** [comment]
I wonder if we could create a LemMinx extension to support JSF?

**Comment by angelozerr** [comment]
> (1) write a LemMinx extension to bind https://github.com/jbosstools/jbosstools-javaee/tree/main/jsf

Indeed, but I fear it can be a big work. If you could be interested to work on it, please ask me. The Maven support from Eclipse IDE uses https://github.com/eclipse/lemminx-maven which is based on LemMinx. The idea is to follow the same idea.

> (2) use that extension within the generic editor.

Eclipse IDE for Java integrates lemminx and lemminx-maven, so you should do nothing, just declare an extension point which load LemMinx extension for JSF in the classpath of lemminx.

**Comment by akurtakov** [comment]
Just an idea - you may consider asking https://github.com/eclipse/lsp4jakarta project about JSF/JSP support too. This project might be more interested or even have something in the plan (all of that is just my thoughts).
