### ISSUE TITLE
Local build with "mvn clean verify" fails

### ISSUE THREAD

**Issue by vogella** [mickaelistria/eclipse-bluesky#18]
If I clone the repo and use "mvn clean verify" I get an error:

[INFO] Unpacking org.objectweb.asm_5.2.0.v20170126-0011...
[INFO] Resolving class path of MavenProject: org.eclipse.bluesky:org.eclipse.bluesky:0.1.0-SNAPSHOT @ /home/vogella/git/eclipse-bluesky/org.eclipse.bluesky/pom.xml
[INFO] Computing target platform for MavenProject: org.eclipse.bluesky:org.eclipse.bluesky.feature:0.1.0-SNAPSHOT @ /home/vogella/git/eclipse-bluesky/org.eclipse.bluesky.feature/pom.xml
[INFO] Resolving dependencies of MavenProject: org.eclipse.bluesky:org.eclipse.bluesky.feature:0.1.0-SNAPSHOT @ /home/vogella/git/eclipse-bluesky/org.eclipse.bluesky.feature/pom.xml
[INFO] Resolving class path of MavenProject: org.eclipse.bluesky:org.eclipse.bluesky.feature:0.1.0-SNAPSHOT @ /home/vogella/git/eclipse-bluesky/org.eclipse.bluesky.feature/pom.xml
[INFO] Computing target platform for MavenProject: org.eclipse.bluesky:repository:0.1.0-SNAPSHOT @ /home/vogella/git/eclipse-bluesky/repository/pom.xml
[INFO] Resolving dependencies of MavenProject: org.eclipse.bluesky:repository:0.1.0-SNAPSHOT @ /home/vogella/git/eclipse-bluesky/repository/pom.xml
[INFO] {osgi.os=linux, osgi.ws=gtk, org.eclipse.update.install.features=true, osgi.arch=x86_64}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: repository raw:0.1.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):0.1.0-SNAPSHOT
[ERROR]   Missing requirement: repository raw:0.1.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):0.1.0-SNAPSHOT requires 'com.google.guava [18.0.0.v20161115-1643]' but it could not be found
[ERROR] 
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: org.eclipse.bluesky:repository:0.1.0-SNAPSHOT @ /home/vogella/git/eclipse-bluesky/repository/pom.xml: See log for details -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException

**Comment by mickaelistria** [comment]
Fixed with #19

**Comment by vogella** [comment]
Build requires local npm installed. Works finally for me after installing that.
