### ISSUE TITLE
JSON Schema Support

### ISSUE THREAD

**Issue by angelozerr** [mickaelistria/eclipse-bluesky#25]
I have implemented quicly JSON Schema Support (see my PR at https://github.com/angelozerr/eclipse-bluesky/commit/73fd3da30160071e2e432210dc1d9e94c2dea817). 

Here a demo:

![jsonschema](https://user-images.githubusercontent.com/1932211/29415223-9c123b56-8362-11e7-8a00-4f62acbafd9c.gif)

To do that, I need to send custom notification `json/schemaAssociations` with mapping between pattern (ex: package.json) and URL of the schema to use. To send this custom notification I have extended LanguageClientImpl by adding `onReady` in `LanguageClientImpl `:

```
	public void onReady() {

	} 
```
In ProjectSpecificLanguageServerWrapper, I call this method

```
initializeFuture = languageServer.initialize(initParams).thenApply(res -> {
	initializeResult = res;
	client.onReady(); // HERE I HAVE ADDED THE CALL OF onReady
	return res;
});
```

Perhaps there is an another clean mean? Hope lsp4e will support this onReady feature.

**Comment by angelozerr** [comment]
I have created a bug in lsp4e at https://bugs.eclipse.org/bugs/show_bug.cgi?id=521065

**Comment by mickaelistria** [comment]
See how the CSS LS handles a similar scenario: https://github.com/mickaelistria/eclipse-bluesky/blob/master/org.eclipse.bluesky/src/org/eclipse/bluesky/CSSLanguageServer.java#L64 . It basically sends a message after is receives confirmation of successful initialization.

**Comment by mickaelistria** [comment]
Just on a side note, this feature is super useful, thanks!

**Comment by angelozerr** [comment]
> See how the CSS LS handles a similar scenario: https://github.com/mickaelistria/eclipse-bluesky/blob/master/org.eclipse.bluesky/src/org/eclipse/bluesky/CSSLanguageServer.java#L64 . It basically sends a message after is receives confirmation of successful initialization.

Many thanks for your help! I have done a PR https://github.com/mickaelistria/eclipse-bluesky/pull/27

> Just on a side note, this feature is super useful, thanks!

Glad it please you!

**Comment by mickaelistria** [comment]
PR merged! Thanks a lot!
