### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by mickaelistria** [mickaelistria/eclipse-bluesky#4]
On Windows, the language servers seem to give no response.

**Comment by jabby** [comment]
On windows, I get the following error when I tried to autocomplete a package.json file with bluesky: 

see: https://dev.eclipse.org/recommenders/community/aeri/v2/#!/submissions/KREVamlKQyOWSAVqpFSLmAL2lBNngvQULlEgM3vwwDF7iLgmuRdaPJZZZVzwDYPh

Here is the package.json file : 

`{
  "name": "eclipseDemoCampNantes2017angularjs",
  "private": true,
  "devDependencies": {
    "autoprefixer-core": "^5.2.1",
    "grunt": "^0.4.5",
    "grunt-angular-templates": "^0.5.7",
    "grunt-concurrent": "^1.0.0",
    "grunt-contrib-clean": "^0.6.0",
    "grunt-contrib-concat": "^0.5.0",
    "grunt-contrib-connect": "^0.9.0",
    "grunt-contrib-copy": "^0.7.0",
    "grunt-contrib-cssmin": "^0.12.0",
    "grunt-contrib-htmlmin": "^0.4.0",
    "grunt-contrib-imagemin": "^1.0.0",
    "grunt-contrib-jshint": "^0.11.0",
    "grunt-contrib-uglify": "^0.7.0",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-filerev": "^2.1.2",
    "grunt-google-cdn": "^0.4.3",
    "grunt-jscs": "^1.8.0",
    "grunt-newer": "^1.1.0",
    "grunt-ng-annotate": "^0.9.2",
    "grunt-postcss": "^0.5.5",
    "grunt-svgmin": "^2.0.0",
    "grunt-usemin": "^3.0.0",
    "grunt-wiredep": "^2.0.0",
    "jasmine-core": "^2.5.2",
    "jit-grunt": "^0.9.1",
    "jshint-stylish": "^1.0.0",
    "karma": "^1.3.0",
    "karma-jasmine": "^1.0.2",
    "karma-phantomjs-launcher": "^1.0.2",
    "phantomjs-prebuilt": "^2.1.13",
    "time-grunt": "^1.0.0"
  },
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "test": "karma start test/karma.conf.js"
  }
}
`

**Comment by mickaelistria** [comment]
Do you have node available in your PATH? If not, your case may be a correlate of #3

**Comment by jabby** [comment]
You are right. Node is not available in my path. I will retry at the end of the week.

**Comment by mickaelistria** [comment]
https://github.com/mickaelistria/eclipse-bluesky/commit/5be3b82b276a87c900dd2c27dee8fc7212e0c5a4 should have fixed issues on Windows. Feel free to reopen this ticket if necessary.
