### ISSUE TITLE
less & scss support

### ISSUE THREAD

**Issue by angelozerr** [mickaelistria/eclipse-bluesky#42]
less and scss doesn't work because it misses grammar. It should be cool to add those grammars and language configuration for thoses languages.

It should better too to consume VSCode css textmate https://github.com/Microsoft/vscode/blob/master/extensions/css/syntaxes/css.tmLanguage.json (to fix for CSS https://github.com/eclipse/tm4e/issues/135)

@jabby I think you could create a little PR for that (without your vue contribution), tell me if you have time, otherwise I will do it.

**Comment by jabby** [comment]
@angelozerr I miss this issue. I will do a PR  tomorrow.

**Comment by angelozerr** [comment]
Thanks @jabby for your help!

**Comment by jabby** [comment]
Maybe we can close this issue.

**Comment by mickaelistria** [comment]
Yes. Fixed with https://github.com/mickaelistria/eclipse-bluesky/commit/9129818234766bbed93d6a8f2c9f134fc2fed74e . Thanks a lot @jabby !
