### ISSUE TITLE
Add Windows & OSX CI with GitHub Actions

### ISSUE THREAD

**Issue by AObuchow** [mickaelistria/eclipse-bluesky#439]
It'd be very useful to have a CI for building & testing Wild Web Developer on Windows & OSX.

Windows CI was just recently added to LemMinX-Maven [here](https://github.com/eclipse/lemminx-maven/commit/4ed31a89bb63ed365b0c52164c0db43d57e9fc02).

**Comment by mickaelistria** [comment]
No news for a while, let's close.
