### ISSUE TITLE
Quick start guide

### ISSUE THREAD

**Issue by PhaserEditor2D** [mickaelistria/eclipse-bluesky#54]
Hi,

I installed Blue Sky but I don't know how to make it work. I see there is a Language Server preference page where I can add Content Type - Run Configuration associations but I don't know what to do here. I do not find any Lang Server Run Configuration.

**Comment by mickaelistria** [comment]
It should just work without extra step. Could it be that your node.js version is not compatible? See #55

**Comment by boniatillo-com** [comment]
I just updated to node v6.11.3 and still not work.

I see in the Error Log view a lot of messages like these:

```
RequestMessage
{
  "jsonrpc": "2.0",
  "id": "17",
  "method": "textDocument/completion",
  "params": {
    "textDocument": {
      "uri": "file:///C:/Users/.../eclipse_bluesky/eclipse/workspace/demo/demo.js"
    },
    "uri": "file:///C:/Users/.../eclipse_bluesky/eclipse/workspace/demo/demo.js",
    "position": {
      "line": 0,
      "character": 0
    }
  }
}
```

```
ResponseMessage
{
  "jsonrpc": "2.0",
  "id": "17",
  "result": {
    "isIncomplete": true,
    "items": []
  }
}
```

**Comment by boniatillo-com** [comment]
I just created a general project with an empty demo.js file. I press Ctrl+Space to see the completions but not completions are shown.

**Comment by boniatillo-com** [comment]
Well, I created a CSS file, and completions works. Even, I created an index.html file and works the javascript completions inside a script tag. So I guess the problem is just about to javascript files.

**Comment by mickaelistria** [comment]
I'm using node 7.x locally and it works for me. The CSS and JS language server are distinct, so it's possible that the CSS is fine with node 6.x whereas the JS one is not.

**Comment by boniatillo-com** [comment]
Installed node 8 and failed, now I gave to downgrade :(

**Comment by boniatillo-com** [comment]
Ok, it is not working with node 7.10.1, I think the node version is not the problem here.

**Comment by mickaelistria** [comment]
Ok, thanks for trying. It might be some URL pattern issues with the JS server ( https://github.com/sourcegraph/javascript-typescript-langserver ). I only tried it on Linux... Maybe @angelozerr or @jabby have a clue?

**Comment by jabby** [comment]
Now I am on fedora too... Sorry.

**Comment by angelozerr** [comment]
@boniatillo-com you try bluesky from github sources? 

If it that :

 * edit https://github.com/mickaelistria/eclipse-bluesky/blob/master/org.eclipse.bluesky/language-servers/package.json
 * remove all dependencies except javascript-typescript-langserver
 * do a npm install to install  javascript-typescript-langserver

**Comment by boniatillo-com** [comment]
@angelozerr I installed it with the marketplace client. I will try with the sources.

**Comment by angelozerr** [comment]
@boniatillo-com You will have compilation problem in your plugin.xml I think because bluesky uses the new reconciler extension point of GenericEdtor, but it's not a problem for js (only for css color).

**Comment by PhaserEditor2D** [comment]
Hi @angelozerr yes, I am getting compilation problems, a missing `org.eclipse.ui.genericeditor.reconcilers` extension point. How can I fix it? I want to start collaborating on this.

**Comment by PhaserEditor2D** [comment]
Yes, it works now with 4.8
