### ISSUE TITLE
Add screnshots to https://marketplace.eclipse.org

### ISSUE THREAD

**Issue by paulvi** [mickaelistria/eclipse-bluesky#58]
Please add screenshots to https://marketplace.eclipse.org/content/bluesky-web-development-eclipse-ide-experimental

**Comment by mickaelistria** [comment]
Can you please provide some screenshots that you think are the best for the Marketplace entry?

**Comment by paulvi** [comment]
I cannot tell what would be the best, but there is already 1 screenshot in the root of this git repository.

**Comment by mickaelistria** [comment]
Done.
