### ISSUE TITLE
Rename project for move to Eclipse.org

### ISSUE THREAD

**Issue by mickaelistria** [mickaelistria/eclipse-bluesky#69]
Following #64 
In https://bugs.eclipse.org/bugs/show_bug.cgi?id=536650 , the Eclipse IP Team reported that Eclipse BlueSky is not allowed as a project name because of high risk of trademark issues. So we need to consider some new names. 
We're moving discussion about finding a new name from Bugzilla to here.

Current proposals are (list update as discussion progresses):
- WEB4e
- Eclipse Wild Web Developer/IDE
- Eclipse Webdev Workbench
- Eclipse WebNG

Once we have a curated list, if necessary, we'll run a round of votes to pick only the top 3 and submit them to Eclipse legal team for review.

**Comment by mickaelistria** [comment]
My comments
* Web4e: 👎 I think this doesn't sound like an interesting name for the target audience of the project
* Eclipse Wild Web Developer: 👍
* Eclipse Wild Web IDE: 👎 it's a bit dangerous that this get rid as Eclipse Wild (Web IDE) which may imply it's an IDE running over the web.
* Eclipse Webdev Workbench:  👍
* Eclipse WebNG: 👎 as I find it unclear it's about tools, but if we call it something like "webdev-ng" or "webtools-ng" (which I believe is not allowed because there is already a WebTools Platform project) or "web-somethingthatsoundslikeitsatools-ng", I'll like it better.

**Comment by paulvi** [comment]
While "blue sky" became general,  
how about "Blue Wild" or "Wild Blue"

second :+1: Wild Web Developer

or "World Wild Web Developer"

**Comment by jabby** [comment]
* Web4e: 👎 as Mickael, I don't think it's good for target audience
* Eclipse Wild Web Developer: 👍 
* Eclipse Wild Web IDE:  I like the name but I think Mickael is right.
* Eclipse Webdev Workbench:  👎 I don't like the name. At least for some french people. It reminds me this company https://www.pcsoft.fr/ and the [poor sexist marketing done](https://www.google.com/search?biw=1842&bih=998&tbm=isch&sa=1&ei=cU9QW7WpJeLSgAah4ryICA&q=windev+pub&oq=windev+pub&gs_l=img.3..0l2j0i24k1l5.36371.36996.0.37085.4.4.0.0.0.0.191.360.0j2.2.0....0...1c.1.64.img..2.2.360...0i30k1j0i8i30k1.0.VuInAU8QwJI)
* Eclipse WebNG: 👎 
* World Wild Web Developer : why not. I like the name but it's maybe to long ?

**Comment by mickaelistria** [comment]
Name `Eclipse Wild Web Developer` was approved and will be used by the project.
We need to rename the bundles/packages before migrating.

**Comment by jabby** [comment]
Thanks Mickael for leading thebug on eclipse bugzilla. 

As you explain, we need to rename bundles and packaging before migrating. 
I can do that next week. But I don't know how to proceed. 

Should we replace bluesky by wildwebdeveloper inn bundles and packages? Should we use underscore between words?

**Comment by jabby** [comment]
Maybe we can use `wwd` for wild web developer in packages and bundles. Like jdt does with his own project.
I will create a PR with this idea next week.

**Comment by mickaelistria** [comment]
I'm afraid there are already several things using "wwd" as acronym and don't see much benefit in using `wwd` rather than `wildwebdeveloper` in package name. I'd be in favor of using `org.eclipse.wildwebdeveloper` as package and bundle prefix everywhere. It's a few more character, but way less risks of confusion and more simple navigation.

**Comment by jabby** [comment]
Ok I will create a PR tomorrow morning.

**Comment by angelozerr** [comment]
Thanks @jabby !
