### ISSUE TITLE
css formatting: disable line break between css class names

### ISSUE THREAD

**Issue by nimo23** [mickaelistria/eclipse-bluesky#997]
Actually when formatting css in generic editor, it formats this:

```
html, body {
	margin: 0;
	padding: 0;
}
```

to this:

```
/** I don't want line breaks between html and body */
html,
body { 
	margin: 0;
	padding: 0;
}
```

Would be nice to add an option to **disable** line breaks between css identifiers (classes-name, id).

**Comment by angelozerr** [comment]
I created à PR to provide CSS format preferences at https://github.com/eclipse/wildwebdeveloper/pull/962 bit it requires some changes to lsp4e @mickaelistria 

I will check if the vscode CSS langage server format convers your issue
